package gov.epa.seqapass.backend.serviceThread;

import gov.epa.seqapass.backend.domain.NCBIKeeper;
import gov.epa.seqapass.backend.domain.NCBIProvider;
import gov.epa.seqapass.backend.externalProcess.ProcessProvider;
import gov.epa.seqapass.backend.externalProcess.ProcessTypeKeeper;
import gov.epa.seqapass.common.LevelOneReportRow;
import gov.epa.seqapass.common.LevelThreeRequestableRow;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;

public class RunLevel3 {
	
	private static Logger logger = LogManager.getLogger(RunLevel3.class);
	
	private JdbcTemplate jdbcTemplate;
	private NCBIProvider ncbiProvider;
	private int accessionRunId = -1;
	private int userId = -1;
	private int level3RunId = -1;
	private String jobName = "";
	private String templateInputString;
	private String additionalComparisonsInputString;
	private List<String> accessionTargets;

	/**
	 * The allFastaDefs is an array of one line strings each <b><u>not</u> starting with '&gt;'</b> . The content is either supplied by the
	 * user or generated by blastdbcmd (or both). It is interleaved with the allFastaSeqs to create the full fasta file to be run through
	 * COBALT. The zeroth item is the template fasta definition.
	 */
	private List<String> allFastaDefs = new ArrayList<String>();

	/**
	 * The allFastaSeqs is an array of (potentially multiline) amino acid sequences. The content is either supplied by the user or generated
	 * by blastdbcmd (or both). It is interleaved with the allFastaDefs to create the full fasta file to be run through COBALT. The zeroth
	 * item is the template fasta sequence.
	 */
	private List<String> allFastaSeqs = new ArrayList<String>();

	private String fullFastaPath;
	private BLASTTools blastTools;
	private BLASTTools2 blastTools2;

	public RunLevel3(BLASTTools blastTools, JdbcTemplate template, NCBIKeeper NCBIKeeper, LevelThreeRequestableRow levelThreeRequestableRow) {
		this.jdbcTemplate = template;
		this.ncbiProvider = NCBIKeeper.getPreferredNCBIProvider();
		this.blastTools = blastTools;
		this.blastTools2 = blastTools.getBlastTools2();
		this.accessionRunId = levelThreeRequestableRow.getAccessionRunId();
		this.userId = levelThreeRequestableRow.getUserId();
		this.jobName = levelThreeRequestableRow.getJobName();
		this.templateInputString = levelThreeRequestableRow.getTemplate();
		this.additionalComparisonsInputString = levelThreeRequestableRow.getAdditionalComparisons();
		this.accessionTargets = levelThreeRequestableRow.getAccessionTargets();
	}

	public boolean dispose() {
		return false;
	}

	public boolean kill() {
		return false;
	}

	/**
	 * This method sets up a run (and returns null) or returns a string explanation for why the setup failed. Its parameters are already
	 * loaded into the RunLevel3 object, mostly from the levelThreeReportRow loaded upon instantiation.
	 * 
	 * @return null if no problem, or a String with the error message to report to the user
	 */
	public String setupAndReportFailure() {
		try {
			jdbcTemplate.queryForObject("SELECT id FROM level3_run WHERE accession_run_id = ? AND user_id = ? AND job_name = ?", int.class,
					accessionRunId, userId, jobName); // NO NEED TO CAPTURE id, IT WILL FAIL THE try IF IT DOES NOT EXIST
			return "This run name is already selected";
		} catch (DataAccessException e1) {
			// DO NOTHING, it just means the job is available
		}
		if (jobName.matches("[^+ a-zA-Z0-9_-]")) {
			return "Job name must be alphanumeric or space, plus, minus, or underscore";
		}
		if (jobName.length() > 63) {
			return "Job name must be 63 characters or fewer";
		}

		String possibleFailure = parseTemplateInputString();
		if (possibleFailure != null) {
			return possibleFailure;
		}

		possibleFailure = parseAdditionalComparisonsInputString();
		if (possibleFailure != null) {
			return possibleFailure;
		}

		// NOW GET NEW JOB ID
		try {
			level3RunId = blastTools.insertLevel3RunReturnId(accessionRunId, userId, jobName, allFastaDefs.get(0));
		} catch (SQLException e) {
			return "Could not submit Level 3 job";
		}
		String outputFileRoot = ncbiProvider.getPathTempFasta() + "/level3-" + level3RunId;
		fullFastaPath = outputFileRoot + ".fsa";
		return null;
	}

	private String parseTemplateInputString() {
		// First possibility: user supplied fasta with def. so --> Confirm validity and separate parts
		if (templateInputString.startsWith(">")) {
			String[] parts = templateInputString.split("[\\x00\\n\\r]", 2);
			if (parts[0].matches("[^ -~]")) { // REJECT NON-ASCII CHARACTERS AND <CR> <TAB> <LF> TYPE CHARS
				return "Template definition must contain only printable ASCII characters";
			}
			if (parts[0].length() > 240) {
				return "Template definition must must be 239 characters or fewer";
			}
			String cleanedSeq = parts[1].replaceAll("[\\r -]", "");
			if (cleanedSeq.matches(".*[^ACDEFGHIKLMNPQRSTUVWXY\\n].*")) {
				return "Template sequence must contain only 1-letter amino acid sequences or X or <CR>";
			}
			// First one, so don't need to confirm that there is not already one
			allFastaDefs.add("(user defined) " + parts[0].trim().substring(1));
			allFastaSeqs.add(cleanedSeq.trim());
			return null; // All's well
		}

		// Second possibility: user supplied accession id so --> Confirm validity, get fasta, and separate parts
		String templateTrim = templateInputString.trim();
		String correctedAccesssionId = blastTools.getCorrectAccessionFromAccessionIdName(templateTrim);
		if (correctedAccesssionId == null) {
			// System.out.println("failure with template: " + templateTrim);
			logger.error("Accession ID of template not found; failure with template: {}", templateTrim);
			return "Accession ID of template not found";
		}
		if (!correctedAccesssionId.equals(templateTrim)) {
			// System.out.println("Corrected template: " + correctedAccesssionId);
			logger.warn("Corrected template: {}", correctedAccesssionId);
		}
		// First one, so don't need to confirm that there is not already one
		allFastaDefs.add(correctedAccesssionId);

		String[] fastaParts = blastTools.getFastaPartsFromAccession(correctedAccesssionId);
		if (fastaParts == null) {
			return "Could not get sequence from " + templateInputString;
		}
		allFastaSeqs.add(fastaParts[1]);
		return null; // All's well
	}

	/**
	 * This method takes a sequence of zero or more accession ids followed by zero or more fasta sequences and creates a fasta by running
	 * blastdbcmd to lookup fasta content for accession ids, then merging with subsequence fasta content. It returns failed: with a relevant
	 * message if the input format is incorrect or accession ids are not in the database
	 * 
	 * @param additionalComparisons
	 * @return a fasta formatted string, ready to add to the subsequent string (which must all be generated from valid accession ids)
	 */
	private String parseAdditionalComparisonsInputString() {
		String[] accsNfastas = additionalComparisonsInputString.split(">");
		if (!accsNfastas[0].equals("")) {
			String[] accessionsList = accsNfastas[0].split("[\\x00\\n\\r]+");
			for (String accessionCandidate : accessionsList) {
				String accessionCandidateTrim = accessionCandidate.trim();

				if (accessionCandidateTrim.matches(".*[^A-Z\\._0-9:=,].*")) {
					return "Failed - Accession id: " + accessionCandidateTrim + " has disallowed characters";
				}
				String correctedAccession = blastTools.getCorrectAccessionFromAccessionIdName(accessionCandidateTrim);
				if (correctedAccession == null) {
					return "Failed - Accession id: " + accessionCandidateTrim + " not found in database";
				}

				String[] fastaParts = blastTools.getFastaPartsFromAccession(correctedAccession);
				if (fastaParts == null) {
					return "Failed - Could not find fasta for accession id: " + accessionCandidateTrim;
				}

				if (allFastaDefs.contains(correctedAccession)) {
					continue;
				}
				allFastaDefs.add(correctedAccession);
				allFastaSeqs.add(fastaParts[1]);
			}
		}
		for (int i = 1; i < accsNfastas.length; i++) {
			String fastaCandidate = accsNfastas[i].replaceAll("\\r", "");
			String gapsRemoved = fastaCandidate.replaceAll("[\\n]+", "\n");
			if (!gapsRemoved.matches("^[^\\n]+\\n[ACDEFGHIKLMNPQRSTUVWXY\\n]+$")) {
				// System.out.println("fastaCandidate: " + gapsRemoved);
				logger.info("Failed - Fasta # {} is not formatted properly or has non amino acid characters present",  gapsRemoved);
				return "Failed - Fasta # " + gapsRemoved + " is not formatted properly or has non amino acid characters present";
			}
			String fastaDef = gapsRemoved.substring(0, gapsRemoved.indexOf("\n")).trim();
			String fastaSeq = gapsRemoved.substring(gapsRemoved.indexOf("\n")).trim();
			if (fastaDef.length() > 239) {
				logger.error("Failed - fasta definition exceeded 239 characters: {}", fastaDef);
				return "Failed - fasta definition exceeded 239 characters: " + fastaDef;
			}
			String modFastaDef = "(user defined) " + fastaDef;
			if (allFastaDefs.contains(modFastaDef)) {
				logger.error("Failed - can not duplicate fasta definition: {}", fastaDef);
				return "Failed - can not duplicate fasta definition: " + fastaDef;
			}
			allFastaDefs.add(modFastaDef);
			allFastaSeqs.add(fastaSeq);
		}
		return null;
	}

	/**
	 * This method runs Level 3 analysis assuming the accessionRunId class variable has been set, and the template sequence has been defined
	 * using either a user-supplied fasta or an accessionId. The return is the level3_run id number.
	 * 
	 * @param
	 * @return int - the level3_run id number for the newly created run. The status can be accessed using this number.
	 */
	public int run() {
		if (accessionRunId < 0 || level3RunId < 0) {
			//System.out.println("Something wrong with level 3 run:  level3RunId, accessionRunId (in order) are:" + level3RunId + ", "
			//		+ accessionRunId);
			logger.error("Something wrong with level 3 run:  level3RunId, accessionRunId (in order) are: {}, {}", 
					level3RunId, accessionRunId);
			return -1;
		}

		//Need to ensure accessionTargets are ordered by percent similarity (same order as in levelOneReport)
		//This is because cobalt results can depend on the order of accessions
		List<LevelOneReportRow> levOneReport = blastTools2.getReportService().getLevelOneReport(accessionRunId);
		List<String> origAccessionTargets = new ArrayList<String>(accessionTargets);
		accessionTargets.clear();
		for (LevelOneReportRow row: levOneReport) {
		   if (origAccessionTargets.contains(row.getAccession())) {
			   accessionTargets.add(row.getAccession());
		   }
		}
		
		String possibleFailure = createAccessionTargetsSingleFasta();
		if (possibleFailure != null) {
			// System.out.println("Failed because: " + possibleFailure);
			logger.error("Failed because: {}", possibleFailure);
		}

		possibleFailure = concatenateFastaPartsSaveToFile();
		if (possibleFailure != null) {
			// System.out.println("Failed because: " + possibleFailure);
			logger.error("Failed because: {}", possibleFailure);
		}

		ProcessProvider level3run = new ProcessProvider();
		level3run.setUserID(0);
		level3run.setJobID(0);
		level3run.setProcessType(ProcessTypeKeeper.getProcessTypeProviderByName(ProcessTypeKeeper.runCobalt));
		level3run.setExecPath(ncbiProvider.getCobaltExecPath());
		List<String> argVals = new ArrayList<String>();
		// System.out.println("fullFastaPath is " + fullFastaPath);
		logger.info("fullFastaPath is {}", fullFastaPath);
		argVals.add(fullFastaPath);
		argVals.add(ncbiProvider.getCobaltDataPath()); // preferred general
		//argVals.add("regular");
		argVals.add("se-b15");
		argVals.add("0.003");
		argVals.add("T");
		level3run.setArgVals(argVals);
		String level3fastaOutput = null;
		blastTools2.updateLevel3Status(level3RunId, "started");
		boolean onlyOneCluster = false;
		try {
			String[] cobaltResults = level3run.timeRun();
			level3fastaOutput = cobaltResults[0];
			String stdErr = cobaltResults[1];
			// System.out.println("Cobalt stderr: " + stdErr);
			logger.info("Cobalt stderr: {}", stdErr);
			blastTools.logJobTime("level3Cobalt", accessionRunId, 1, allFastaDefs.size(), stdErr);

			if (stdErr.matches(".*only one cluster.*")) {
				onlyOneCluster = true;
			}
		} catch (InterruptedException | IOException e) {
			e.printStackTrace();
			blastTools2.updateLevel3Status(level3RunId, "failed");
			return -1;
		}
		if (level3fastaOutput == null || level3fastaOutput.length() < 10) {
			blastTools2.updateLevel3Status(level3RunId, "failed");
			if (level3fastaOutput == null) {
				logger.warn("Cobalt results null");
			} else {
				logger.warn("Cobalt results only {} characters",level3fastaOutput.length());
			}
			return -1;
		}
		blastTools2.updateLevel3Status(level3RunId, "analyzing");
		//System.out.println("About to try to save level 3 results with level3RunId, allFastaDefs.size() : " + level3RunId + " - "
		//		+ allFastaDefs.size());
		logger.debug("About to try to save level 3 results with level3RunId, allFastaDefs.size() : {} - {}", 
				level3RunId, allFastaDefs.size());

		if (!blastTools.saveCobaltResults(level3RunId, allFastaDefs, level3fastaOutput)) {
			// System.out.println("Failed to write cobalt results");
			logger.error("Failed to write cobalt results");
		}

		blastTools2.setLevel3RunComplete(level3RunId);

		blastTools2.createLevelThreeReport(accessionRunId, level3RunId, -1, 1);

		int toxCastUserID = blastTools2.getToxCastUserId();
		if (userId == toxCastUserID) {
			blastTools2.createLevelThreeReport(accessionRunId, level3RunId, userId, 2); // creates for public_reports destination
		}

		if (onlyOneCluster) {
			blastTools2.updateLevel3Status(level3RunId, "complete: 1 cluster");
			return 0;
		}
		blastTools2.updateLevel3Status(level3RunId, "complete");
		return 0;
	}

	/**
	 * This creates the fasta file necessary for Level 3 analysis. If the template protein is specified as a fasta file, it is added after
	 * the muultiple fasta file is created. Otherwise it is placed at the front of the list (and removed if found subsequently).
	 * 
	 * @param accessionsForTemp
	 *            - the first protein is used as the template
	 * @return String[2] full paths to the temporary fasta files: single, multiple
	 */
	private String createAccessionTargetsSingleFasta() {

		// System.out.println("Trying createLevel3TempFasta");
		logger.debug("Trying createLevel3TempFasta");

		int ncbiVersionID = ncbiProvider.getId();
		// System.out.println("ncbiVersionID = " + ncbiVersionID);

		// System.out.println("accessionsForTemp.size = " + accessionTargets.size());
		
		logger.info("ncbiVersionID = {}", ncbiVersionID);

		logger.info("accessionsForTemp.size = {}", accessionTargets.size());

		if (accessionTargets.size() == 0) {
			return null; // No problem here, just no accession targets to add
		}

		for (String accessionTarget : accessionTargets) {
			String[] fastaParts = blastTools.getFastaPartsFromAccession(accessionTarget);
			if (fastaParts == null) {
				logger.error("Could not create fasta for accession: {}", accessionTarget);
				return "Could not create fasta for accession: " + accessionTarget;
			}

			if (allFastaDefs.contains(accessionTarget)) {
				continue;
			}
			allFastaDefs.add(accessionTarget);
			allFastaSeqs.add(fastaParts[1]);
		}
		return null;
	}

	private String concatenateFastaPartsSaveToFile() {
		if (allFastaDefs.size() != allFastaSeqs.size()) {
			logger.error("Failed because number of fasta defs: {} does not equal the number of fasta sequences: {}",
					allFastaDefs.size(), allFastaSeqs.size());
			return "Failed because number of fasta defs: " + allFastaDefs.size() + " does not equal the number of fasta sequences: "
					+ allFastaSeqs.size();
		}
		StringBuilder stringToWrite = new StringBuilder();
		for (int i = 0; i < allFastaDefs.size(); i++) {
			stringToWrite.append(">" + allFastaDefs.get(i) + "\n" + allFastaSeqs.get(i) + "\n");
		}

		try {
			PrintWriter fastaOut = new PrintWriter(fullFastaPath);
			fastaOut.print(stringToWrite.toString());
			fastaOut.flush();
			fastaOut.close();
		} catch (Exception e) {
			logger.error("Writing final Fasta file failed: {}", e);
			return "Writing final Fasta file failed";
		}
		return null;
	}

	public int getAccession_run_id() {
		return accessionRunId;
	}

	public void setAccession_run_id(int accession_run_id) {
		this.accessionRunId = accession_run_id;
	}

	public int getLevel3RunId() {
		return level3RunId;
	}

	public void setLevel3RunId(int level2RunId) {
		this.level3RunId = level2RunId;
	}

	public String getFullFastaPath() {
		return fullFastaPath;
	}

	public void setFullFastaPath(String fullFastaPath) {
		this.fullFastaPath = fullFastaPath;
	}

	public List<String> getAccessionTargets() {
		return accessionTargets;
	}

	public void setAccessionTargets(List<String> accessionTargets) {
		this.accessionTargets = accessionTargets;
	}

	public String getStatus() {
		if (level3RunId < 0) {
			logger.error("Not run: {}", level3RunId);
			return "Not run";
		}
		String query = "SELECT status FROM level3_run WHERE id = ?";
		try {
			return jdbcTemplate.queryForObject(query, String.class, level3RunId);
		} catch (DataAccessException e1) {
			logger.error("Job Not Found! - {}", e1);
			return "Job Not Found!";
		}
	}
}
